apiVersion: apps/v1
#kind: Deployment
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
              name: mongo
          envFrom:
            - configMapRef:
                name: mongo-config
          volumeMounts:
            - mountPath: /data/db
              name: mongo
      volumes:
        - name: mongo
          persistentVolumeClaim:
            claimName: mongo-pv-claim
      
      
